### ISSUE TITLE
[Bug]: OpenPose Editor tab doesn't show up at all in latest ForgeUI

### ISSUE THREAD

**Issue by dextfox** [huchenlei/sd-webui-openpose-editor#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I had installed the Openpose Editor on ForgeUI (cu124_torch24)but the tab doesn't show up at all, ControlNet is pre-installed on ForgeUI so this is not a solution like A1111. I installed a a new ForgeUI because I thought it was a Lob HUB SD skin issue, but No! the original Openpose Editor doesn't show up again. Any solution?

### Steps to reproduce the problem

0

### What should have happened?

Openpose Editor should be at tabs

### Commit where the problem happens

webui: webui_forge_cu124_torch24(Forge Flux Support)
controlnet: latest
openpose-editor: latest

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
0
```

### Console logs

```Shell
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-552-g953e3f39
Commit hash: 953e3f39833d9de742223be882b86c5be0efaa1c
Launching Web UI with arguments:
Total VRAM 8188 MB, total RAM 32508 MB
pytorch version: 2.4.0+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Laptop GPU : native
Hint: your device supports --cuda-malloc for potential speed improvements.
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: False
C:\Users\AFRAA\Documents\Stable D\Forge Flux\webui_forge_cu124_torch24\system\python\lib\site-packages\transformers\utils\hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Using pytorch cross attention
Using pytorch attention for VAE
ControlNet preprocessor location: C:\Users\AFRAA\Documents\Stable D\Forge Flux\webui_forge_cu124_torch24\webui\models\ControlNetPreprocessor
Loading additional modules ... done.
2024-12-02 10:36:43,721 - ControlNet - INFO - ControlNet UI callback registered.
*** Error executing callback ui_tabs_callback for C:\Users\AFRAA\Documents\Stable D\Forge Flux\webui_forge_cu124_torch24\webui\extensions\sd-webui-deforum\scripts\deforum.py
    Traceback (most recent call last):
      File "C:\Users\AFRAA\Documents\Stable D\Forge Flux\webui_forge_cu124_torch24\webui\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "C:\Users\AFRAA\Documents\Stable D\Forge Flux\webui_forge_cu124_torch24\webui\extensions\sd-webui-deforum\scripts\deforum_helpers\ui_right.py", line 38, in on_ui_tabs
        with gr.Row(elem_id='deforum_progress_row').style(equal_height=False, variant='compact'):
    AttributeError: 'Row' object has no attribute 'style'

---
Model selected: {'checkpoint_info': {'filename': 'C:\\Users\\AFRAA\\Documents\\Stable D\\Forge Flux\\webui_forge_cu124_torch24\\webui\\models\\Stable-diffusion\\STOIQONewrealityFLUXSD_F1DAlpha.safetensors', 'hash': 'a3bee872'}, 'additional_modules': [], 'unet_storage_dtype': None}
Using online LoRAs in FP16: False
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
🤯 LobeTheme: Initializing...
IIB Database file has been successfully backed up to the backup folder.
Startup time: 31.4s (prepare environment: 9.1s, import torch: 13.5s, initialize shared: 0.2s, other imports: 1.1s, load scripts: 2.2s, initialize google blockly: 2.7s, create ui: 2.0s, gradio launch: 1.1s).
Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False}
[GPU Setting] You will use 87.49% GPU memory (7163.00 MB) to load weights, and use 12.51% GPU memory (1024.00 MB) to do matrix computation.
```

### Browser logs

0

### Additional information

0

**Comment by dextfox** [comment]
0

**Comment by superfarkh** [comment]
i have the same problem too.
